
import { getList } from 'country-list-with-dial-code-and-flag'

export const primaryColor = '#0d6efd';
export const disabledColor = '#A9A9A9';
export const inputComponentHeight = '38px';
export const defaultCountryDialCode = '+98';
export const minInputsHeight = 40;

export const countries0 = [
    {value: 0, label: 'Afghanistan'},
    {value: 1, label: 'Albania'},
    {value: 2, label: 'Algeria'},
    {value: 3, label: 'Andorra'},
    {value: 4, label: 'Angola'},
    {value: 5, label: 'Antigua & Deps'},
    {value: 6, label: 'Argentina'},
    {value: 7, label: 'Armenia'},
    {value: 8, label: 'Australia'},
    {value: 9, label: 'Austria'},
    {value: 10, label: 'Azerbaijan'},
    {value: 11, label: 'Bahamas'},
    {value: 12, label: 'Bahrain'},
    {value: 13, label: 'Bangladesh'},
    {value: 14, label: 'Barbados'},
    {value: 15, label: 'Belarus'},
    {value: 16, label: 'Belgium'},
    {value: 17, label: 'Belize'},
    {value: 18, label: 'Benin'},
    {value: 19, label: 'Bhutan'},
    {value: 20, label: 'Bolivia'},
    {value: 21, label: 'Bosnia Herzegovina'},
    {value: 22, label: 'Botswana'},
    {value: 23, label: 'Brazil'},
    {value: 24, label: 'Brunei'},
    {value: 25, label: 'Bulgaria'},
    {value: 26, label: 'Burkina'},
    {value: 27, label: 'Burundi'},
    {value: 28, label: 'Cambodia'},
    {value: 29, label: 'Cameroon'},
    {value: 30, label: 'Canada'},
    {value: 31, label: 'Cape Verde'},
    {value: 32, label: 'Central African Rep'},
    {value: 33, label: 'Chad'},
    {value: 34, label: 'Chile'},
    {value: 35, label: 'China'},
    {value: 36, label: 'Colombia'},
    {value: 37, label: 'Comoros'},
    {value: 38, label: 'Congo'},
    {value: 39, label: 'Congo {Democratic Rep}'},
    {value: 40, label: 'Costa Rica'},
    {value: 41, label: 'Croatia'},
    {value: 42, label: 'Cuba'},
    {value: 43, label: 'Cyprus'},
    {value: 44, label: 'Czech Republic'},
    {value: 45, label: 'Denmark'},
    {value: 46, label: 'Djibouti'},
    {value: 47, label: 'Dominica'},
    {value: 48, label: 'Dominican Republic'},
    {value: 49, label: 'East Timor'},
    {value: 50, label: 'Ecuador'},
    {value: 51, label: 'Egypt'},
    {value: 52, label: 'El Salvador'},
    {value: 53, label: 'Equatorial Guinea'},
    {value: 54, label: 'Eritrea'},
    {value: 55, label: 'Estonia'},
    {value: 56, label: 'Ethiopia'},
    {value: 57, label: 'Fiji'},
    {value: 58, label: 'Finland'},
    {value: 59, label: 'France'},
    {value: 60, label: 'Gabon'},
    {value: 61, label: 'Gambia'},
    {value: 62, label: 'Georgia'},
    {value: 63, label: 'Germany'},
    {value: 64, label: 'Ghana'},
    {value: 65, label: 'Greece'},
    {value: 66, label: 'Grenada'},
    {value: 67, label: 'Guatemala'},
    {value: 68, label: 'Guinea'},
    {value: 69, label: 'Guinea-Bissau'},
    {value: 70, label: 'Guyana'},
    {value: 71, label: 'Haiti'},
    {value: 72, label: 'Honduras'},
    {value: 73, label: 'Hungary'},
    {value: 74, label: 'Iceland'},
    {value: 75, label: 'India'},
    {value: 76, label: 'Indonesia'},
    {value: 77, label: 'Iran'},
    {value: 78, label: 'Iraq'},
    {value: 79, label: 'Ireland {Republic}'},
    {value: 80, label: 'Israel'},
    {value: 81, label: 'Italy'},
    {value: 82, label: 'Ivory Coast'},
    {value: 83, label: 'Jamaica'},
    {value: 84, label: 'Japan'},
    {value: 85, label: 'Jordan'},
    {value: 86, label: 'Kazakhstan'},
    {value: 87, label: 'Kenya'},
    {value: 88, label: 'Kiribati'},
    {value: 89, label: 'Korea North'},
    {value: 90, label: 'Korea South'},
    {value: 91, label: 'Kosovo'},
    {value: 92, label: 'Kuwait'},
    {value: 93, label: 'Kyrgyzstan'},
    {value: 94, label: 'Laos'},
    {value: 95, label: 'Latvia'},
    {value: 96, label: 'Lebanon'},
    {value: 97, label: 'Lesotho'},
    {value: 98, label: 'Liberia'},
    {value: 99, label: 'Libya'},
    {value: 100, label: 'Liechtenstein'},
    {value: 101, label: 'Lithuania'},
    {value: 102, label: 'Luxembourg'},
    {value: 103, label: 'Macedonia'},
    {value: 104, label: 'Madagascar'},
    {value: 105, label: 'Malawi'},
    {value: 106, label: 'Malaysia'},
    {value: 107, label: 'Maldives'},
    {value: 108, label: 'Mali'},
    {value: 109, label: 'Malta'},
    {value: 110, label: 'Marshall Islands'},
    {value: 111, label: 'Mauritania'},
    {value: 112, label: 'Mauritius'},
    {value: 113, label: 'Mexico'},
    {value: 114, label: 'Micronesia'},
    {value: 115, label: 'Moldova'},
    {value: 116, label: 'Monaco'},
    {value: 117, label: 'Mongolia'},
    {value: 118, label: 'Montenegro'},
    {value: 119, label: 'Morocco'},
    {value: 120, label: 'Mozambique'},
    {value: 121, label: 'Myanmar, {Burma}'},
    {value: 122, label: 'Namibia'},
    {value: 123, label: 'Nauru'},
    {value: 124, label: 'Nepal'},
    {value: 125, label: 'Netherlands'},
    {value: 126, label: 'New Zealand'},
    {value: 127, label: 'Nicaragua'},
    {value: 128, label: 'Niger'},
    {value: 129, label: 'Nigeria'},
    {value: 130, label: 'Norway'},
    {value: 131, label: 'Oman'},
    {value: 132, label: 'Pakistan'},
    {value: 133, label: 'Palau'},
    {value: 134, label: 'Panama'},
    {value: 135, label: 'Papua New Guinea'},
    {value: 136, label: 'Paraguay'},
    {value: 137, label: 'Peru'},
    {value: 138, label: 'Philippines'},
    {value: 139, label: 'Poland'},
    {value: 140, label: 'Portugal'},
    {value: 141, label: 'Qatar'},
    {value: 142, label: 'Romania'},
    {value: 143, label: 'Russian Federation'},
    {value: 144, label: 'Rwanda'},
    {value: 145, label: 'St Kitts & Nevis'},
    {value: 146, label: 'St Lucia'},
    {value: 147, label: 'Saint Vincent & the Grenadines'},
    {value: 148, label: 'Samoa'},
    {value: 149, label: 'San Marino'},
    {value: 150, label: 'Sao Tome & Principe'},
    {value: 151, label: 'Saudi Arabia'},
    {value: 152, label: 'Senegal'},
    {value: 153, label: 'Serbia'},
    {value: 154, label: 'Seychelles'},
    {value: 155, label: 'Sierra Leone'},
    {value: 156, label: 'Singapore'},
    {value: 157, label: 'Slovakia'},
    {value: 158, label: 'Slovenia'},
    {value: 159, label: 'Solomon Islands'},
    {value: 160, label: 'Somalia'},
    {value: 161, label: 'South Africa'},
    {value: 162, label: 'South Sudan'},
    {value: 163, label: 'Spain'},
    {value: 164, label: 'Sri Lanka'},
    {value: 165, label: 'Sudan'},
    {value: 166, label: 'Suriname'},
    {value: 167, label: 'Swaziland'},
    {value: 168, label: 'Sweden'},
    {value: 169, label: 'Switzerland'},
    {value: 170, label: 'Syria'},
    {value: 171, label: 'Taiwan'},
    {value: 172, label: 'Tajikistan'},
    {value: 173, label: 'Tanzania'},
    {value: 174, label: 'Thailand'},
    {value: 175, label: 'Togo'},
    {value: 176, label: 'Tonga'},
    {value: 177, label: 'Trinidad & Tobago'},
    {value: 178, label: 'Tunisia'},
    {value: 179, label: 'Turkey'},
    {value: 180, label: 'Turkmenistan'},
    {value: 181, label: 'Tuvalu'},
    {value: 182, label: 'Uganda'},
    {value: 183, label: 'Ukraine'},
    {value: 184, label: 'United Arab Emirates'},
    {value: 185, label: 'United Kingdom'},
    {value: 186, label: 'United States'},
    {value: 187, label: 'Uruguay'},
    {value: 188, label: 'Uzbekistan'},
    {value: 189, label: 'Vanuatu'},
    {value: 190, label: 'Vatican City'},
    {value: 191, label: 'Venezuela'},
    {value: 192, label: 'Vietnam'},
    {value: 193, label: 'Yemen'},
    {value: 194, label: 'Zambia'},
    {value: 195, label: 'Zimbabwe'},
]

export const countries = () => {
    let temp = [];
    //{ "name": "string", "dial_code": "string", "code": "string", "flag": "string" }
    getList().forEach(element => {
        temp.push({ value: element.code, label: element.name })
    });
    return temp;
}

const countryCodesFunction = () => {
    let temp = [...getList()];
    //{ "name": "string", "dial_code": "string", "code": "string", "flag": "string" }
    temp.forEach(element => {
        element.value = element.code;
        element.filterText = `${element.name} ${element.dial_code}`;
        element.label = <div className='d-flex flex-row gap-1' >
            <span className='flag-emoji' >{element.flag}</span>
            <span >{element.name}</span>
            <span >{`(${element.dial_code})`}</span>
        </div>
        element.label2 = <div className='d-flex flex-row gap-1' >
            <span className='flag-emoji' >{element.flag}</span>
            <span >{element.dial_code}</span>
        </div>
    });
    return temp;
}

export const countryCodes = countryCodesFunction();

export const DegreeList = [
    {value: "Diploma", label: "Diploma", fa: "دیپلم"},
    {value: "Associate", label: "Associate's Degree", fa: "فوق دیپلم"},
    {value: "Bachelor", label: "Bachelor's Degree", fa: "کارشناسی"},
    {value: "Master", label: "Master's Degree", fa: "کارشناسی ارشد"},
    {value: "Doctoral", label: "Doctoral", fa: "پزشکی"},
    {value: "PhD", label: "Doctor of Philosophy", fa: "دکترای حرفه ای"},
    {value: "PostDoc", label: "Postdoctoral", fa: "پست دکتری"},
]

export const textLabels = {
    from: {en: 'From', fa: 'از'},
    to: {en: 'to', fa: 'تا'},
    now: {en: 'Now', fa: 'کنون'},
    ok: {en: 'OK', fa: 'تأیید'},
    cancel: {en: 'Cancel', fa: 'لغو'},
    add: {en: 'Add', fa: 'افزودن'},
    edit: {en: 'Edit', fa: 'ویرایش'},
    saveChanges: {en: 'Save Changes', fa: 'ذخیره تغییرات'},
    clearForm: {en: 'Clear Form', fa: 'پاک کردن فرم'},
    changePass: {en: 'Change Password', fa: 'تغییر کلمه عبور'},
    fillSample: {en: 'Fill Sample', fa: 'نمونه پر شده'},

    personal: {en: 'Personal Info', fa: 'مشخصات فردی'},
    personalTitle: {en: 'Personal Information', fa: 'مشخصات فردی'},
    education: {en: 'Educational Info', fa: 'اطلاعات تحصیلی'},
    educationTitle: {en: 'Educational Information', fa: 'اطلاعات تحصیلی'},
    workExp: {en: 'Work Experiences', fa: 'سوابق کاری'},
    privacy: {en: 'Privacy', fa: 'حریم خصوصی'},

    country: {en: 'Country', fa: 'کشور'},
    state: {en: 'State', fa: 'استان'},
    city: {en: 'City', fa: 'شهر'},
    startDate: {en: 'Start Date', fa: 'تاریخ شروع'},
    endDate: {en: 'End Date', fa: 'تاریخ پایان'},
    yes: {en: 'Yes', fa: 'بلی'},
    no: {en: 'No', fa: 'خیر'},

    firstName: {en: 'First Name', fa: 'نام'},
    lastName: {en: 'Last Name', fa: 'نام خانوادگی'},
    birthDate: {en: 'Birth Date', fa: 'تاریخ تولد'},
    nationality: {en: 'Nationality', fa: 'ملیت'},
    married: {en: 'Are you married', fa: 'آیا ازدواج کرده اید؟'},
    children: {en: 'Number of Children', fa: 'تعداد فرزندان'},
    mobileNumber: {en: 'Mobile Number', fa: 'شماره تلفن همراه'},
    phoneNumber: {en: 'Phone Number', fa: 'شماره تلفن'},
    email: {en: 'Email Address', fa: 'آدرس پست الکترونیک'},
    zipCode: {en: 'Zip Code', fa: 'کد پستی'},
    address: {en: 'Address', fa: 'آدرس'},

    degree: {en: 'Degree', fa: 'مدرک تحصیلی'},
    university: {en: 'University/College/Institue', fa: 'دانشگاه / مؤسسه'},
    major: {en: 'Major', fa: 'رشته'},
    orientation: {en: 'Orientation', fa: 'گرایش'},
    gpa: {en: 'GPA', fa: 'معدل'},
    stillStudent: {en: "I'm still student", fa: 'هنوز دانشجو / دانش آموز هستم'},

    job: {en: 'Job Title', fa: 'عنوان شغلی'},
    organization: {en: 'Company / Organization', fa: 'شرکت / سازمان / کارخانه'},
    responsibilities: {en: 'Responsibilities / Achievments', fa: 'مسئولیت ها / دستاوردها'},
    stillWorking: {en: "I'm still working at this position", fa: 'هنوز مشول به کار هستم'},

    username: {en: 'Username', fa: 'نام کاربری'},
    newpassword: {en: 'New Password', fa: 'کلمه عبور جدید'},
    repeatNewPassword: {en: 'Repeat New Password', fa: 'تکرار کلمه عبور جدید'},
    dontShowEmail: {
        en: 'Do not show my email to others (Show only to my contacts)', 
        fa: 'آدرس پست الکترونیک من فقط به مخاطبین من نشان داده شود'
    },
    sendNotif: {en: 'Send me notification', fa: 'اعلانات برای من ارسال شود'},
    sendAdminMessages: {
        en: 'Send me important messages from admin',
        fa: 'پیام های مهم مدیر برای من ارسال شود'
    },

    allFields: {en: 'All fields are needed', fa: 'تمامی فیلدها باید تکمیل شوند'},
    startDateNotFormat: {
        en: 'Start date is not in correct format', 
        fa: 'تاریخ شروع در فرمت مناسب نیست'
    },
    startDateValid: {en: 'Enter a valid start date', fa: 'یک تاریخ شروع معتبر وارد نمایید'},
    endDateNotFormat: {
        en: 'End date is not in correct format', 
        fa: 'تاریخ پایان در فرمت مناسب نیست'
    },
    endDateValid: {en: 'Enter a valid end date', fa: 'یک تاریخ پایان معتبر وارد نمایید'},
    gpaValid: {en: 'Enter a valid GPA', fa: 'یک مقدار معتبر برای معدل وارد نمایید'},
    removeCard: {
        en: 'You are going to remove the card.', 
        fa: 'شما در حال حذف کارت هستید.'
    },
    emailValid: {en: 'Enter a valid email address', fa: 'یک آدرس پست الکترونیک معتبر وارد نمایید'},
    mobileValid: {en: 'Enter a valid mobile number', fa: 'یک شماره تلفن همراه معتبر وارد نمایید'},
    phoneValid: {en: 'Enter a valid phone number', fa: 'یک شماره تلفن معتبر وارد نمایید'},
    birthDateValid: {en: 'Birth date is not in correct format', fa: 'تاریخ تولد در فرمت مناسب نیست'},
    zipCodeValid: {en: 'Enter a valid Zip Code', fa: 'یک کد پستی معتبر وارد نمایید'},
    smallPassword: {en: 'Password must be at least 5 characters', fa: 'کلمه عبور باید حداقل 5 کاراکتر داشته باشد'},
    passwordRepeat: {en: 'Password and its repeat are not the same', fa: 'کلمه عبور و تکرار آن با هم یکسان نیستند'},

    contactInfo: {en: 'Contact Info', fa: 'اطلاعات تماس'},
    printProfile: {en: 'Print Profile', fa: 'چاپ پروفایل'},
    marriedStatus: {en: 'Married', fa: 'متأهل'},
    notMarriedStatus: {en: 'Unmarried', fa: 'مجرد'},

    diploma: {en: "Diploma", fa: "دیپلم"},
    associate: {en: "Associate's Degree", fa: "فوق دیپلم"},
    bachelor: {en: "Bachelor's Degree", fa: "کارشناسی"},
    master: {en: "Master's Degree", fa: "کارشناسی ارشد"},
    doctoral: {en: "Doctoral", fa: "پزشکی"},
    phD: {en: "Doctor of Philosophy", fa: "دکترای حرفه ای"},
    postDoc: {en: "Postdoctoral", fa: "پست دکتری"},
}

export const modeClasses = {
    textColorPrimary: {light: 'color-primary', dark: 'color-white'},
    textColor: {light: 'color-dark', dark: 'color-white'},
    textColorWhite: {light: 'color-white', dark: 'color-dark'},
    bgNormal: {light: '', dark: 'bg-dark'},
    to: {light: '', dark: ''},

}
